-- ============================================================================
-- DREAM STITCH By Sk — bedding catalogue
--
-- Adds the bedding columns the storefront reads, clears the previous
-- clothing demo rows, and seeds categories and products priced in PKR.
-- Safe to re-run: every statement is idempotent.
--
-- Generated by scripts/gen_bedding_seed.py — edit that file, not this one.
-- ============================================================================

-- ----------------------------------------------------------------------
-- 1. Bedding columns
-- ----------------------------------------------------------------------
ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS images           TEXT[],
    ADD COLUMN IF NOT EXISTS sizes            TEXT[],
    ADD COLUMN IF NOT EXISTS colors           TEXT[],
    ADD COLUMN IF NOT EXISTS fabric           TEXT,
    ADD COLUMN IF NOT EXISTS pieces           TEXT,
    ADD COLUMN IF NOT EXISTS compare_at_price NUMERIC(10, 2)
        CHECK (compare_at_price IS NULL OR compare_at_price >= 0);

-- ----------------------------------------------------------------------
-- 2. Retire the earlier demo catalogues (electronics, then clothing)
--    Products referenced by a placed order are left alone (order_items
--    is ON DELETE RESTRICT), so this never breaks order history.
-- ----------------------------------------------------------------------
DELETE FROM public.products p
 WHERE p.category_id IN (
           '11111111-1111-1111-1111-111111111111'::uuid,
           '22222222-2222-2222-2222-222222222222'::uuid,
           '33333333-3333-3333-3333-333333333333'::uuid,
           '44444444-4444-4444-4444-444444444444'::uuid,
           'c1000000-0000-4000-8000-000000000001'::uuid,
           'c1000000-0000-4000-8000-000000000002'::uuid,
           'c1000000-0000-4000-8000-000000000003'::uuid,
           'c1000000-0000-4000-8000-000000000004'::uuid,
           'c1000000-0000-4000-8000-000000000005'::uuid,
           'c1000000-0000-4000-8000-000000000006'::uuid,
           'c1000000-0000-4000-8000-000000000007'::uuid,
           'c1000000-0000-4000-8000-000000000008'::uuid
       )
   AND NOT EXISTS (
           SELECT 1 FROM public.order_items oi WHERE oi.product_id = p.id
       );

DELETE FROM public.categories c
 WHERE c.id IN (
           '11111111-1111-1111-1111-111111111111'::uuid,
           '22222222-2222-2222-2222-222222222222'::uuid,
           '33333333-3333-3333-3333-333333333333'::uuid,
           '44444444-4444-4444-4444-444444444444'::uuid,
           'c1000000-0000-4000-8000-000000000001'::uuid,
           'c1000000-0000-4000-8000-000000000002'::uuid,
           'c1000000-0000-4000-8000-000000000003'::uuid,
           'c1000000-0000-4000-8000-000000000004'::uuid,
           'c1000000-0000-4000-8000-000000000005'::uuid,
           'c1000000-0000-4000-8000-000000000006'::uuid,
           'c1000000-0000-4000-8000-000000000007'::uuid,
           'c1000000-0000-4000-8000-000000000008'::uuid
       )
   AND NOT EXISTS (
           SELECT 1 FROM public.products p WHERE p.category_id = c.id
       );


-- ----------------------------------------------------------------------
-- 3. Categories
-- ----------------------------------------------------------------------
INSERT INTO public.categories (id, name, slug, description, image_url) VALUES
    ('d1000000-0000-4000-8000-000000000001'::uuid, 'Pure Cotton', 'pure-cotton', 'Densely woven pure cotton that stays cool through summer and softens with every wash.', 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80&auto=format&fit=crop'),
    ('d1000000-0000-4000-8000-000000000002'::uuid, 'Cotton Zeen', 'cotton-zeen', 'Smooth, close-woven cotton zeen with a gentle drape and a forgiving, crease-resistant finish.', 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80&auto=format&fit=crop'),
    ('d1000000-0000-4000-8000-000000000003'::uuid, 'Cotton Satin', 'cotton-satin', 'Cotton finished in a satin weave for a low sheen that catches the light without shouting.', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80&auto=format&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url   = EXCLUDED.image_url,
    updated_at  = NOW();


-- ----------------------------------------------------------------------
-- 4. Products
-- ----------------------------------------------------------------------
INSERT INTO public.products (
    category_id, name, slug, description, price, compare_at_price, stock,
    image_url, images, sizes, colors, fabric, pieces,
    is_featured, rating, reviews_count
) VALUES
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Sahar Printed Pure Cotton King Bedsheet',
        'sahar-printed-pure-cotton-king',
        'Our everyday king set in 100% pure cotton, printed on a soft ivory ground. Cut with a full drop on both sides so it stays tucked when you turn over, with double-stitched hems and reinforced corners. Breathes through the hottest months and softens rather than thins with every wash.',
        6490, 7990, 38,
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1583845112203-29329902332e?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Ivory', 'Lilac', 'Sage']::text[],
        'Pure Cotton', '1 bedsheet + 2 pillow covers',
        true, 4.8, 212
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Sahar Printed Pure Cotton Single Bedsheet',
        'sahar-printed-pure-cotton-single',
        'The single-bed version of our best-selling pure cotton set, in the same print and the same weave. Sized for a standard single mattress with a generous drop, finished with one matching pillow cover.',
        3490, 4290, 52,
        'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Single']::text[],
        ARRAY['Ivory', 'Lilac', 'Sage']::text[],
        'Pure Cotton', '1 bedsheet + 1 pillow cover',
        false, 4.7, 96
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Neelum Solid Pure Cotton King Bedsheet',
        'neelum-solid-pure-cotton-king',
        'A plain-dyed pure cotton king set for people who would rather the bed stayed quiet. Reactive-dyed so the colour survives the laundry, with a crisp hand on day one that turns soft by the second week.',
        5490, NULL, 44,
        'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['White', 'Pearl', 'Slate', 'Charcoal']::text[],
        'Pure Cotton', '1 bedsheet + 2 pillow covers',
        true, 4.9, 178
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Chandni Block Print Pure Cotton King Bedsheet',
        'chandni-block-print-pure-cotton-king',
        'Hand-blocked in small runs, so no two sets carry exactly the same register. Printed on the same pure cotton base we use across the house, then washed once before packing to take the stiffness out and set the colour.',
        7490, 8990, 21,
        'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Ivory', 'Orchid', 'Indigo']::text[],
        'Pure Cotton', '1 bedsheet + 2 pillow covers',
        true, 4.9, 143
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Roshni Pure Cotton Single Bedsheet',
        'roshni-pure-cotton-single',
        'A plain, hard-working single set for guest rooms and children''s beds. Pure cotton, machine washable, and cheap enough to keep two in the cupboard.',
        2990, NULL, 63,
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1505692952047-1a78307da8f2?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Single']::text[],
        ARRAY['White', 'Blush', 'Sage']::text[],
        'Pure Cotton', '1 bedsheet + 1 pillow cover',
        false, 4.6, 74
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Bagh Floral Pure Cotton King Bedsheet',
        'bagh-floral-pure-cotton-king',
        'A full-bleed floral drawn in-house and printed edge to edge, so the pattern carries over the drop instead of stopping at the mattress. Pure cotton throughout, with matching pillow covers.',
        6990, NULL, 29,
        'https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1616137466211-f939a420be84?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1592229505726-ca121723b8ef?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Ivory', 'Rose', 'Teal']::text[],
        'Pure Cotton', '1 bedsheet + 2 pillow covers',
        false, 4.7, 108
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Zeen Everyday King Bedsheet',
        'zeen-everyday-king',
        'The set we sell most of. Cotton zeen is close-woven and slightly heavier than plain cotton, which is why it drapes properly over a deep mattress and comes out of the wash without much creasing. Made for households that change the bed on a Sunday and want it to look made.',
        4990, 5990, 57,
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Pearl', 'Lavender', 'Slate']::text[],
        'Cotton Zeen', '1 bedsheet + 2 pillow covers',
        true, 4.8, 264
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Zeen Everyday Single Bedsheet',
        'zeen-everyday-single',
        'Our everyday cotton zeen in a single size. Same weave, same forgiving finish, sized for a standard single mattress with one matching pillow cover.',
        2990, 3590, 71,
        'https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Single']::text[],
        ARRAY['Pearl', 'Lavender', 'Slate']::text[],
        'Cotton Zeen', '1 bedsheet + 1 pillow cover',
        false, 4.7, 121
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Mehr Striped Cotton Zeen King Bedsheet',
        'mehr-striped-cotton-zeen-king',
        'A woven stripe rather than a printed one, so the line runs through the cloth and cannot wash off. Cotton zeen holds a stripe cleanly without puckering along the hem.',
        5490, 6490, 33,
        'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1616593969747-4797dc75033e?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Pearl', 'Orchid', 'Navy']::text[],
        'Cotton Zeen', '1 bedsheet + 2 pillow covers',
        true, 4.8, 156
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Sada Solid Cotton Zeen King Bedsheet',
        'sada-solid-cotton-zeen-king',
        'Plain cotton zeen in four house colours. The quiet option — no print, no border, just an evenly dyed ground and a well-finished hem.',
        4790, NULL, 48,
        'https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['White', 'Lilac', 'Sage', 'Graphite']::text[],
        'Cotton Zeen', '1 bedsheet + 2 pillow covers',
        false, 4.6, 89
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Noor Geometric Cotton Zeen King Bedsheet',
        'noor-geometric-cotton-zeen-king',
        'A small repeating geometric that reads as texture from across the room and as a pattern up close. Printed on cotton zeen, which takes fine detail without bleeding.',
        5990, NULL, 26,
        'https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1629949009765-40fc74c9ec21?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Ivory', 'Aubergine', 'Teal']::text[],
        'Cotton Zeen', '1 bedsheet + 2 pillow covers',
        false, 4.7, 97
    ),
    (
        'd1000000-0000-4000-8000-000000000002'::uuid,
        'Zeen Crease-Free Single Bedsheet',
        'zeen-crease-free-single',
        'Finished for minimum creasing, which matters most on a single bed that gets made in a hurry. Cotton zeen, machine washable, ready to use straight off the line.',
        3290, NULL, 40,
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1503174971373-b1f69850bded?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Single']::text[],
        ARRAY['White', 'Pearl', 'Blush']::text[],
        'Cotton Zeen', '1 bedsheet + 1 pillow cover',
        false, 4.5, 62
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Lustre Cotton Satin King Bedsheet',
        'lustre-cotton-satin-king',
        'Cotton, finished in a satin weave for a low, liquid sheen that catches the light without shouting. Cool to the touch and noticeably smoother against skin than a plain weave — the set you make the bed with when guests are coming.',
        8990, 10990, 24,
        'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1616627561950-9f746e330187?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Pearl', 'Lilac', 'Charcoal']::text[],
        'Cotton Satin', '1 bedsheet + 2 pillow covers',
        true, 4.9, 187
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Lustre Cotton Satin Single Bedsheet',
        'lustre-cotton-satin-single',
        'The single version of our cotton satin set. Same weave and the same finish, cut for a standard single mattress.',
        5490, NULL, 31,
        'https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Single']::text[],
        ARRAY['Pearl', 'Lilac', 'Charcoal']::text[],
        'Cotton Satin', '1 bedsheet + 1 pillow cover',
        false, 4.8, 73
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Shab Cotton Satin King Bedsheet',
        'shab-cotton-satin-king',
        'Our deepest colourway, dyed on cotton satin so the sheen lifts the colour instead of flattening it. Dark sets show every loose thread, so this one is checked twice before it is folded.',
        9490, NULL, 17,
        'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Aubergine', 'Plum', 'Navy']::text[],
        'Cotton Satin', '1 bedsheet + 2 pillow covers',
        true, 4.9, 132
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Aab Cotton Satin King Bedsheet',
        'aab-cotton-satin-king',
        'A cool, pale cotton satin set for summer. The satin finish keeps it smooth against skin on nights when a heavier weave feels like too much.',
        8490, 9990, 22,
        'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['White', 'Pearl', 'Teal']::text[],
        'Cotton Satin', '1 bedsheet + 2 pillow covers',
        false, 4.8, 104
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Zeb Embroidered Cotton Satin King Bedsheet',
        'zeb-embroidered-cotton-satin-king',
        'Our wedding set. Cotton satin with a hand-guided embroidered border along the top sheet and both pillow covers. Made in small numbers and finished slowly — allow a little longer if the colour you want is not in stock.',
        12990, 15990, 9,
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1604709177225-055f99402ea3?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['King Size']::text[],
        ARRAY['Ivory', 'Blush', 'Plum']::text[],
        'Cotton Satin', '1 bedsheet + 2 pillow covers',
        true, 5.0, 48
    ),
    (
        'd1000000-0000-4000-8000-000000000001'::uuid,
        'Custom Size Pure Cotton Bedsheet',
        'custom-size-pure-cotton',
        'Pure cotton, cut to your bed rather than to a size chart. Send us your mattress width, mattress length and the drop you want on each side, and we will confirm the exact price before anything is cut. Dispatched in 7 to 10 working days. Priced from the figure shown — your final price depends on your measurements.',
        7490, NULL, 99,
        'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1522444195799-478538b28823?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Custom Size']::text[],
        ARRAY['White', 'Ivory', 'Lilac', 'Sage', 'Charcoal']::text[],
        'Pure Cotton', 'Made to Order · cut to your measurements',
        true, 4.9, 61
    ),
    (
        'd1000000-0000-4000-8000-000000000003'::uuid,
        'Custom Size Cotton Satin Bedsheet',
        'custom-size-cotton-satin',
        'Our cotton satin, made to your measurements. Same weave and finish as the stocked sets, cut for a frame no standard size fits. Send three numbers and we will price it the same working day. Dispatched in 7 to 10 working days.',
        10990, NULL, 99,
        'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1200&q=80&auto=format&fit=crop',
        ARRAY['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1200&q=80&auto=format&fit=crop', 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1200&q=80&auto=format&fit=crop']::text[],
        ARRAY['Custom Size']::text[],
        ARRAY['Pearl', 'Lilac', 'Aubergine', 'Navy']::text[],
        'Cotton Satin', 'Made to Order · cut to your measurements',
        false, 4.9, 34
    )
ON CONFLICT (slug) DO UPDATE SET
    category_id      = EXCLUDED.category_id,
    name             = EXCLUDED.name,
    description      = EXCLUDED.description,
    price            = EXCLUDED.price,
    compare_at_price = EXCLUDED.compare_at_price,
    stock            = EXCLUDED.stock,
    image_url        = EXCLUDED.image_url,
    images           = EXCLUDED.images,
    sizes            = EXCLUDED.sizes,
    colors           = EXCLUDED.colors,
    fabric           = EXCLUDED.fabric,
    pieces           = EXCLUDED.pieces,
    is_featured      = EXCLUDED.is_featured,
    rating           = EXCLUDED.rating,
    reviews_count    = EXCLUDED.reviews_count,
    updated_at       = NOW();
